// Mocks generated by Mockito 5.4.5 from annotations
// in eclipse/test/src/modules/home/infra/repositories/nasa_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:eclipse/src/modules/home/infra/repositories/datasource/favorites_datasource.dart'
    as _i5;
import 'package:eclipse/src/modules/home/infra/repositories/datasource/nasa_datasource.dart'
    as _i3;
import 'package:eclipse/src/modules/home/infra/repositories/models/apod_model.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeApodModel_0 extends _i1.SmartFake implements _i2.ApodModel {
  _FakeApodModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [NasaDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockNasaDatasource extends _i1.Mock implements _i3.NasaDatasource {
  @override
  _i4.Future<_i2.ApodModel> getMediaOfDay(String? date) =>
      (super.noSuchMethod(
            Invocation.method(#getMediaOfDay, [date]),
            returnValue: _i4.Future<_i2.ApodModel>.value(
              _FakeApodModel_0(this, Invocation.method(#getMediaOfDay, [date])),
            ),
            returnValueForMissingStub: _i4.Future<_i2.ApodModel>.value(
              _FakeApodModel_0(this, Invocation.method(#getMediaOfDay, [date])),
            ),
          )
          as _i4.Future<_i2.ApodModel>);
}

/// A class which mocks [FavoritesDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockFavoritesDatasource extends _i1.Mock
    implements _i5.FavoritesDatasource {
  @override
  _i4.Future<Set<_i2.ApodModel>> getAll() =>
      (super.noSuchMethod(
            Invocation.method(#getAll, []),
            returnValue: _i4.Future<Set<_i2.ApodModel>>.value(
              <_i2.ApodModel>{},
            ),
            returnValueForMissingStub: _i4.Future<Set<_i2.ApodModel>>.value(
              <_i2.ApodModel>{},
            ),
          )
          as _i4.Future<Set<_i2.ApodModel>>);

  @override
  _i4.Future<void> put(_i2.ApodModel? data) =>
      (super.noSuchMethod(
            Invocation.method(#put, [data]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> remove(_i2.ApodModel? data) =>
      (super.noSuchMethod(
            Invocation.method(#remove, [data]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
