name: eclipse
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  cached_network_image: ^3.4.1
  design_system:
    path: 'packages/design_system/'
  dio: ^5.8.0+1
  envied: ^1.1.1
  flutter:
    sdk: flutter
  flutter_modular: ^6.3.4
  hive: ^2.2.3
  intl: ^0.20.2
  path_provider: ^2.1.5
  video_player: ^2.9.3

dev_dependencies:
  build_runner: ^2.4.15
  envied_generator: ^1.1.1
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  integration_test:
    sdk: flutter
  mockito: ^5.4.5

flutter:
  uses-material-design: true
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
