name: 'Flutter CI'

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  trigger-android-build:
    name: Trigger Android Build
    uses: ./.github/workflows/android_build.yml  # Chama o workflow android_build.yml

  trigger-ios-build:
    name: Trigger iOS Build
    needs: trigger-android-build # Depende do trigger-android-build
    uses: ./.github/workflows/ios_build.yml      # Chama o workflow ios_build.yml