name: Flutter CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: Generate .env
        run: |
          touch .env
          echo { >> .env
          echo \"API_KEY\": \"${{ secrets.API_KEY }}\" >> .env
          echo } >> .env
          cat .env

      - name: Install dependencies
        run: flutter pub get

      - name: Format code
        run: dart format --set-exit-if-changed .

      - name: Statically analyze
        run: flutter analyze .

      - name: Run Tests
        run: flutter test

      - name: Build apk.
        run: flutter build apk --release --dart-define-from-file=.env

      - name: Upload Artifact
        uses: actions/upload-artifact@main
        with:
          name: release-apk
          path: /build/app/outputs/apk/release/app-release.apk
