name: Flutter CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: "17.x"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2.14.0
        with:
          flutter-version: 3.29.0
          channel: stable

      - name: Exibir a versao instalada do Flutter
        run: flutter --version

      - name: Generate .env
        run: |
          touch .env
          echo { >> .env
          echo \"API_KEY\": \"${{ secrets.API_KEY }}\" >> .env
          echo } >> .env
          cat .env

      - name: Install dependencies
        run: flutter pub get

      - name: Run Build Runner
        run: dart run build_runner build -d

      - name: Format code
        run: dart format --set-exit-if-changed .

      - name: Statically analyze
        run: flutter analyze .

      - name: Run Tests
        run: flutter test

      - name: Executar Build para iOS
        run: |
          flutter build ios --simulator --release

      - name: Build apk.
        run: flutter build apk --release

      - name: Upload Artifact
        uses: actions/upload-artifact@main
        with:
          name: release-apk
          path: /build/app/outputs/flutter-apk/app-release.apk
