name: "Build Android"

on:
  workflow_call: # Altere o trigger para workflow_call

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Exibir a versao atual do macOS
        run: sw_vers -productVersion

      - name: Instalar o Flutter
        uses: subosito/flutter-action@v2.14.0
        with:
          flutter-version: 3.29.0
          channel: stable

      - name: Exibir a versao instalada do Flutter
        run: flutter --version

      - name: Informacoes e configuracoes do Flutter
        run: flutter doctor -v

      - name: Clean
        run: flutter clean

      - name: Install dependencies
        run: flutter pub get

      - name: Generate .env
        run: |
          touch .env
          echo "API_KEY=${{secrets.API_KEY }}" >> .env
          cat .env

      - name: Run Build Runner
        run: dart run build_runner build -d

      - name: Executar Build para iOS
        run: |
          flutter build ios --simulator --debug

      - name: Upload Artifact
        uses: actions/upload-artifact@main
        with:
          name: release-ipa
          path: build/ios/iphonesimulator/Runner.app
